# Generated by Django 4.2.7 on 2024-09-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fashion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='user_images')),
                ('gender', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('occassion', models.CharField(max_length=200)),
            ],
        ),
    ]
