# Generated by Django 4.2.7 on 2024-10-06 12:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Fashion', '0002_user_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('c_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Category', models.CharField(max_length=200)),
                ('Color', models.CharField(max_length=200)),
                ('Occassion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='new_user',
            fields=[
                ('u_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('Gender', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Wardrobe',
            fields=[
                ('img_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('img_path', models.ImageField(upload_to='user_images')),
                ('image_name', models.CharField(max_length=1000)),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fashion.new_user')),
            ],
        ),
        migrations.CreateModel(
            name='Rec',
            fields=[
                ('rec_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fashion.category')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fashion.new_user')),
            ],
        ),
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('f_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fashion.category')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fashion.new_user')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='u_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fashion.new_user'),
        ),
        migrations.AddField(
            model_name='category',
            name='w_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fashion.wardrobe'),
        ),
    ]
