# Generated by Django 4.2.7 on 2024-10-06 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fashion', '0003_category_new_user_wardrobe_rec_favourites_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wardrobe',
            old_name='img_id',
            new_name='w_id',
        ),
    ]
