# Generated by Django 4.2.7 on 2024-11-27 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fashion', '0006_question_useranswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_food', models.CharField(max_length=255)),
                ('number_of_guests', models.IntegerField()),
                ('event_type', models.CharField(max_length=100)),
                ('quantity_of_food', models.FloatField()),
                ('storage_conditions', models.CharField(max_length=100)),
                ('purchase_history', models.CharField(max_length=100)),
                ('seasonality', models.CharField(max_length=100)),
                ('preparation_method', models.CharField(max_length=100)),
                ('geographical_location', models.CharField(max_length=100)),
                ('pricing', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('locality', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('cuisine', models.TextField()),
                ('rating', models.FloatField()),
                ('votes', models.IntegerField()),
                ('cost', models.FloatField()),
            ],
        ),
    ]
