# Generated by Django 4.2.7 on 2024-11-27 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fashion', '0007_event_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_capacity', models.FloatField(blank=True, null=True)),
                ('current_requirement', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('contact_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_of_food_donated', models.FloatField()),
                ('donation_date', models.DateTimeField(auto_now_add=True)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='Fashion.ngo')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='Fashion.restaurant')),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='u_id',
        ),
        migrations.RemoveField(
            model_name='category',
            name='w_id',
        ),
        migrations.RemoveField(
            model_name='favourites',
            name='c_id',
        ),
        migrations.RemoveField(
            model_name='favourites',
            name='u_id',
        ),
        migrations.RemoveField(
            model_name='rec',
            name='c_id',
        ),
        migrations.RemoveField(
            model_name='rec',
            name='u_id',
        ),
        migrations.DeleteModel(
            name='user_files',
        ),
        migrations.DeleteModel(
            name='user_new',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wardrobe',
            name='u_id',
        ),
        migrations.RenameField(
            model_name='new_user',
            old_name='Gender',
            new_name='Type',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Favourites',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Rec',
        ),
        migrations.DeleteModel(
            name='UserAnswer',
        ),
        migrations.DeleteModel(
            name='Wardrobe',
        ),
        migrations.AddField(
            model_name='currentbalance',
            name='ngo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='Fashion.ngo'),
        ),
        migrations.AddField(
            model_name='currentbalance',
            name='restaurant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='Fashion.restaurant'),
        ),
    ]
